### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by CBID2** [open-sauced/status.opensauced.pizza#19]
**Describe the bug**
- I clicked on the link to the status' website and it shows a 404 error page 

**To Reproduce**
1. Scroll down the ReadMe file
2. Click on Visit Status' website link 
3. See error page

**Expected behavior**

**Screenshots**
![image](https://github.com/open-sauced/status.opensauced.pizza/assets/105683440/0054c470-2a9e-43cf-b1a5-8b950872ee31)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPad
 - OS: iOS 
 - Browser Safari
 - Version 22

**Additional context**

**Comment by takanome-dev** [comment]
I think the link should be https://status.opensauced.pizza/

**Comment by CBID2** [comment]
> I think the link should be https://status.opensauced.pizza/

Thanks @takanome-dev

**Comment by CBID2** [comment]
.take
