### ISSUE TITLE
[Bug] 404 error when clicked on the Live Status link on the first line of README.md

### ISSUE THREAD

**Issue by adybose** [open-sauced/status.opensauced.pizza#21]
**Describe the bug**
Clicking on the [Live Status](https://deadreyo.github.io/upptime-test) link on [README.md](https://github.com/open-sauced/status/blob/main/README.md) leads to a 404 Not Found page.

**To Reproduce**
1. Go to the repository home page at https://github.com/open-sauced/status
2. Click on the Live Status link on the rendered [README.md](https://github.com/open-sauced/status/blob/main/README.md) file.
3. The page redirects to the URL: https://deadreyo.github.io/upptime-test which is incorrect
4. Also, clicking on the link in the About section of the repository leads to the the wrong page.

**Expected behavior**
The page should point to https://status.opensauced.pizza/
 
**Screenshots**
![259298703-0054c470-2a9e-43cf-b1a5-8b950872ee31](https://github.com/open-sauced/status/assets/13054902/d9b9e9a0-7000-4403-b935-ecfee49445c3)

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser: All Browsers
 - Version: All Versions

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: All OS
 - Browser: All Browsers
 - Version: All versions

**Additional context**
Clicking on the link in the **About** section of the repository also leads to the the wrong page (See Screenshot below). This also needs to be updated which can be done by the Maintainer only.
<img width="1335" alt="Screenshot 2023-08-23 at 10 25 28 PM" src="https://github.com/open-sauced/status/assets/13054902/ec272496-0e57-4af9-a32c-53b21d915155">

**Comment by takanome-dev** [comment]
Well spotted! Same as https://github.com/open-sauced/status/issues/19.

Feel free to take it

**Comment by jpmcb** [comment]
There are a number of places where it looks like that dead link is present:

```
❯ rg "https://Deadreyo.github.io/upptime-test"
README.md
1:# [📈 Live Status](https://Deadreyo.github.io/upptime-test): <!--live status--> **🟩 All systems operational**
11:With [Upptime](https://upptime.js.org), you can get your own unlimited and free uptime monitor and status page, powered entirely by a GitHub repository. We use [Issues](https://github.com/Deadreyo/upptime-test/issues) as incident reports, [Actions](https://github.com/Deadreyo/upptime-test/actions) as uptime monitors, and [Pages](https://Deadreyo.github.io/upptime-test) for the status page.
```

We should fix all of them in one sweep so we don't keep having this issue opened.

**Comment by adybose** [comment]
@jpmcb @takanome-dev I updated the README.md file with the recommended fixes into a branch checked out from `main`. However, I am not able to push my branch. Is there any security check in place that would allow me to push to the repository only if I am added to it first? Kindly let me know, so that I may open the PR for the same.

Thanks 😁

**Comment by takanome-dev** [comment]
That sounds like you didn't fork this repo. Try the following steps:

- fork the repo
- clone the forked repository to your local machine.
- check out a new branch and make the changes
- commit and push your changes in your branch
- open a pr

For more info, see our [docs](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#setup)

**Comment by adybose** [comment]
This PR https://github.com/open-sauced/status/pull/22 fixes it.
